370511: Creating Stub API
DEFRA/stw-stubs pull request #1
Opened 2024-05-09 15:16 UTC by sean-treanor

- Added notifications controller to mock notification creation from IPAFFS notification ms
- Added endpoint to show health and version of service
- Added unit test and integration test projects

2024-05-10 10:21 UTC, reece-bennett requested changes

2024-05-10 10:21 UTC, reece-bennett commented on src/STW.StubApi.Presentation/Properties/launchSettings.json
> +      "launchBrowser": true,
Can we set `launchBrowser` to false, gets annoying when you restart the debug session and it opens another :)

2024-05-10 10:21 UTC, reece-bennett commented on src/STW.StubApi.Presentation/Services/Notification/Helpers/NotificationHelper.cs
> +        return $"DRAFT.GB.{currentYear}.{random}";
Should be submitted not draft I think, at this point we'd expect IPAFFS to do whatever is required to make it submitted, and that's the reference we give back to STW. So prefix would be certificate type

2024-05-10 10:21 UTC, reece-bennett commented on src/STW.StubApi.IntegrationTests/HealthCheckTests.cs
> +        // Arrange / Act
Would you not just specify Act here because there is no setup, just calling the system under test?

2024-05-10 10:21 UTC, reece-bennett commented on src/STW.StubApi.Presentation.UnitTests/Services/Notification/Validators/NotificationValidatorTests.cs
> +    public void IsValid_ReturnsTrue_WhenNotificationDoesNotSatisfyTheSchema()
Test name needs update to ReturnsFalse

2024-05-10 11:50 UTC, reece-bennett approved these changes

2024-05-13 14:07 UTC, kamilmkainos approved these changes

2024-05-14 12:08 UTC, joshuahigginson approved these changes

2024-05-15 14:25 UTC, merged