377003: Implement commodity code stub service endpoints
DEFRA/stw-stubs pull request #5
Opened 2024-06-05 16:57 UTC by joshuahigginson

2024-06-06 09:33 UTC, reece-bennett requested changes

2024-06-06 09:33 UTC, reece-bennett commented on src/STW.StubApi.Presentation/Services/CommodityCode/Models/ChedPSpecies.cs
> +public class ChedPSpecies
Don't capitalise the P `ChedpSpecies`

2024-06-06 12:06 UTC, joshuahigginson commented on src/STW.StubApi.Presentation/Services/CommodityCode/Models/ChedPSpecies.cs
> +public class ChedPSpecies
fixed

2024-06-06 12:08 UTC, reece-bennett approved these changes

2024-06-10 10:59 UTC, reece-bennett commented on src/STW.StubApi.Presentation/Services/CommodityCode/Controllers/CommodityCategoryController.cs
> +        return Ok(CommodityCategoriesHelper.GetCommodityCategory(certType, commodityCode));
If you're always returning a successful response you can just set the return type to be the object returned and drop `Ok()`

2024-06-10 11:23 UTC, kamilmkainos approved these changes

2024-06-12 10:41 UTC, merged